language: swift
osx_image: xcode9.3
branches:
  only:
    - master
before_install:
  - brew update
script:
  - xcodebuild -workspace web3swift.xcworkspace -scheme web3swift_Tests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE" test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
