language: swift
osx_image: xcode9.3
branches:
  only:
    - master
script:
  - xcodebuild -workspace Trust.xcworkspace -scheme Trust -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE" test | xcpretty
